spring:
  application:
    name: xinapi
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3306/xinapi?serverTimezone=GMT%2b8
    username: root
    password: xxxx
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
#  session:
#    cookie:
#      max-age: 86400
#    domain: "#"
  # redis 配置
  redis:
    port: 6379
    host: xxxx
    password: xxxx
server:
  port: 7529
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 86400
      domain: "#"
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

dubbo:
  application:
    name: provider-service
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://xxx:8848

xinapi:
  client:
    access-key: xin
    secret-key: abcdefg